--- 
version: "3.3"
services: 
 mydb: 
  image: db 
  ports: 
    - "3306:3306"
  volumes: 
    - mydb:/var/lib/mysql/
  environment: 
    - MYSQL_ROOT_PASSWORD= root

 vprocache01: 
  image: memcached
  ports: 
   - "11211:11211"

 vpromq01: 
  image: rabbitmq 
  ports: 
   - "15672:15672"
  environment:
   - RABBITMQ_DEFAULT_USER= guest
   - RABBITMQ_DEFAULT_PASSWORD= guest
 
 vproapp: 
  image: app 
  ports: 
   - "8080:8080"
  volumes: 
   - vproapp:/usr/local/tomcat/

 vproweb: 
  image: web
  ports: 
  - "80:80"

volumes: 
  mydb: {}
  vproapp: {} 
